### PR TITLE
Reducers and actions

### PR DESCRIPTION
**Pull request by Chaseknis**
- Add Redux Toolkit
- Create redux directory
- Add store.js, bookSlice.js, and categoriesSlice.js files
- Run linters for errors
- Update README.md file

### CODE REVIEW

**Review by AmaduKamara — COMMENTED** [review]
# Status: Invalid Submission ❌ ❌ ❌

Hi @Chaseknis,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

For this project, you are expected to submit a PR for connecting to the API:

- [ ] You have submitted a project, that is not matched the requirements given. 
- [ ] You are to submit your work for [Bookstore: Connect to API](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/connect_to_api.md), but you submitted reducers and actions work. Kindly resubmit the right PR with solutions for connecting to the API all working as expected 👍🏽

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```

**Comment by Chaseknis** [comment]
@AmaduKamara I'm sorry about that, I tried to undo the submission but it wasn't possible. Thank still.

**Review by Davidosky007 — APPROVED** [review]
Hi @Chaseknis 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Good looking readme file 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Chaseknis** [comment]
thank you @Davidosky007

**Pull request merged**
